### ISSUE TITLE
Tag v0.10.1

### ISSUE THREAD

**Issue by sjkelly** [MikeInnes/Lazy.jl#33]
There seems to be some deprecation warnings that have been fixed, and precompilation enabled since the last release. It would be nice to have a new tagged release. Are there any big issues blocking a new tag?

**Comment by one-more-minute** [comment]
Done at JuliaLang/METADATA.jl/pull/3809

**Comment by bjarthur** [comment]
so close this issue then!  :)

**Comment by MikeInnes** [comment]
Fair point :)
