### ISSUE TITLE
LazyBase

### ISSUE THREAD

**Issue by TotalVerb** [MikeInnes/Lazy.jl#49]
Do you think it would be feasible to create a module that does the following:

- intended for `baremodule` use, as it replaces some `Base` functions with alternatives (does not override them, just defines new ones with the same name)
- most functions from `Base` are re-exported
- functions like `map`, `filter`, `flatten`, etc. are made lazy; indexing replaced by `view` by default
- `ctranspose(f)` defined to strict-ify function `f`, otherwise fall back to standard `ctranspose`. I picked this mostly because it allows `foldr'(x)`, which has precedent in Haskell to strict-ify things

Would such a thing be desirable in Lazy.jl, or perhaps it belongs in a different package entirely?

**Comment by MikeInnes** [comment]
It's an interesting idea but it seems very non-standard / unidiomatic in Julia. I think it probably does make sense to experiment with this in a separate package, and we can think about folding it in if it turns out to be particularly useful.

**Comment by TotalVerb** [comment]
OK, thanks for your feedback. I'll play around with this in a separate package and reopen it if it's useful.
