### ISSUE TITLE
Lazy freezes in Atom

### ISSUE THREAD

**Issue by HamletFr** [MikeInnes/Lazy.jl#90]
When I try to use Lazy inside Atom, Julia freezes. Inside the Terminal outside of atom it works all fine.

The versions are:
```
Julia Version 0.7.0

Lazy v0.13.0
Atom v0.7.3+
Juno v0.5.2+

julia-client 0.7.3
language-julia 0.16.0
```

**Comment by pfitzseb** [comment]
Is there a reason why you're not on the released versions of all those packages? We have 1.0 compatibility for those as of Friday or so. I also can't reproduce any hangs (neither in the editor nor in the built in REPL):
```
julia> using Lazy

julia> @> seq(1:3) drop(1)
(2 3)

(v1.0) pkg>  st
    Status `~/.julia/environments/v1.0/Project.toml`
  [c52e3926] Atom v0.7.3
  [7057c7e9] Cassette v0.1.0
  [28b8d3ca] GR v0.32.2+ [`~/.julia/dev/GR`]
  [e5e0dc1b] Juno v0.5.2
  [50d2b5c4] Lazy v0.13.0
```

**Comment by HamletFr** [comment]
No, there is no specific reason. It was just from before Friday.

The following example freezes in the Atom terminal whereas it works without a problem in a normal terminal window:

```
julia> using Lazy

julia> fibs = @lazy 0:1:(fibs + drop(1, fibs));
```


Von: Sebastian Pfitzner <notifications@github.com>
Antworten an: "MikeInnes/Lazy.jl" <reply@reply.github.com>
Datum: Sonntag, 12. August 2018 um 19:59
An: "MikeInnes/Lazy.jl" <Lazy.jl@noreply.github.com>
Cc: Tileman Conring <tileman@conring-frisius.de>, Author <author@noreply.github.com>
Betreff: Re: [MikeInnes/Lazy.jl] Lazy freezes in Atom (#90)


Is there a reason why you're not on the released versions of all those packages? We have 1.0 compatibility for those as of Friday or so. I also can't reproduce any hangs (neither in the editor nor in the built in REPL):

julia> using Lazy



julia> @> seq(1:3) drop(1)

(2 3)



(v1.0) pkg>  st

    Status `~/.julia/environments/v1.0/Project.toml`

  [c52e3926] Atom v0.7.3

  [7057c7e9] Cassette v0.1.0

  [28b8d3ca] GR v0.32.2+ [`~/.julia/dev/GR`]

  [e5e0dc1b] Juno v0.5.2

  [50d2b5c4] Lazy v0.13.0

**Comment by colemanbroad** [comment]
Same issue. The above example works fine in terminal, but hangs in Juno. Running on 1.1.

```
(v1.1) pkg> st
    Status `~/.julia/environments/v1.1/Project.toml`
  [c52e3926] Atom v0.9.1
  [e5e0dc1b] Juno v0.7.1 ⚲
  [50d2b5c4] Lazy v0.13.2+ #Master (https://github.com/MikeInnes/Lazy.jl.git)
```

**Comment by pfitzseb** [comment]
Ah, I think I know what's going on -- if you have the workspace open, Juno will try to show all values defined in the current scope there. Since `show`ing `fibs` doesn't terminate, Juno will appear to hang.

Imho we should just fix the `show` method here.

**Comment by racinmat** [comment]
Still experiencing it, it ties to go over the expression infinitely, taking single core of my machine and constantly eating more and more ram.

**Comment by AshtonSBradley** [comment]
I am getting the same behavior in Atom, running the README examples...
